spring:
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true #생성된 sql 출력
        format_sql: true #sql 포맷팅 해서 출력
        use_sql_comments: true #테이블과 칼럼 commant 함께 출력
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace #preparedStatement 로 바인딩되는 값 함께출력
  h2:
    console:
      enabled: true
      path: /h2-console